import React, { useEffect, useRef, useState } from 'react';
import { AnimatedOptions } from './AnimatedOptions.jsx';
import assetMap from './asset-map.json';
import { CountUp, DeviceSwap, HeroStage, Parallax, ScreenDeck, useSmoothScroll } from './motion.jsx';

const asset = name => `/assets/${assetMap[name]?.file || name}`;
const store = 'https://apps.apple.com/cn/app/reacl-%E4%B8%AA%E4%BA%BA%E8%BF%90%E5%8A%A8%E8%AE%AD%E7%BB%83/id6775321000';
const phases = [
  ['保护与恢复','从消肿、活动度与基础激活开始，认真做好恢复的第一步。'],
  ['找回步伐','逐步恢复步行与日常活动，建立稳定的动作习惯。'],
  ['建立力量','循序渐进地积累下肢力量，为后续训练打下基础。'],
  ['稳定与控制','关注单腿支撑、平衡和核心稳定，让每一步更有把握。'],
  ['准备跑跳','在合适的进阶条件下，逐步接触冲击与落地训练。'],
  ['跑跳进阶','把力量带进跑跳，继续打磨落地与动作质量。'],
  ['回归运动','结合多方向动作与回归前评估，为重返热爱的运动做好准备。'],
];
const screens = [['今日训练','iphone-daily.png','今天练什么，清楚地安排好。'],['恢复进程','iphone-progress.png','从记录到晋级，看见每一步积累。'],['动作详情','iphone-exercise-detail.png','理解动作要点，再开始练习。']];
const features = [
  {id:'capture',title:'动作捕捉与评估',art:'lab-sls-assessment.png',heading:'把动作里的细节，看清楚。',text:'支持动作可用 iPhone 摄像头计数带练。实验室提供单腿蹲与 CMJ 评估，帮助查看动作控制与落地表现。',notes:['单腿蹲评估 · 阶段 4 起','CMJ 纵跳评估 · 阶段 6 起'],image:'cmj-result.png',caption:'CMJ 评估 · 实际结果示例'},
  {id:'demo',title:'3D 动作演示',art:'lab-cmj-assessment.png',heading:'换个角度，理解怎么练。',text:'在支持的动作详情中查看 3D 演示。App 内可切换视角、缩放与控制播放，结合关节角度理解动作过程。',notes:['动作详情中的 Pro 功能','部分动作提供 3D 演示'],image:'iphone-demo3d.png',caption:'高脚杯深蹲 · App 原生 3D 录屏'},
  {id:'tape',title:'肌贴逐步演示',art:'lab-tape.png',heading:'每一段肌贴，都有步骤。',text:'从锚点位置到铺贴方向，跟着膝盖防护贴扎的 3D 步骤逐段查看。先看清位置，再理解每一步。',notes:['实验室 · 膝盖防护贴扎','髌骨稳定示例'],image:'iphone-tape.png',caption:'髌骨稳定 · App 原生步骤画面'},
];
const comparison = [['每日训练','固定排课','按当天状态调节 · 家中 / 健身房'],['动作库','66 个基础动作','170+ 动作，持续更新'],['饮食','阶段营养指南','每日三餐 + 加餐，支持偏好与换一道'],['阶段解读','—','每次晋级的个性化解读'],['每周回顾','—','训练数据回顾与建议'],['重返运动评估','—','术后满 9 个月 · 评估与报告'],['动作指导与实验室','—','iPhone 摄像头计数 · 动作评估 · 3D 与肌贴步骤']];
function Download({quiet=false,children='下载 iOS App'}) {return <a className={`button ${quiet?'quiet':'primary'}`} href={store} target="_blank" rel="noopener noreferrer">{children}<span aria-hidden="true">↗</span></a>}
function EnvironmentScene({environment}) {
  const ref=useRef(null);
  const [near,setNear]=useState(false),[loaded,setLoaded]=useState([]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){setNear(true);observer.disconnect()}},{rootMargin:'400px'});observer.observe(ref.current);return()=>observer.disconnect()},[]);
  useEffect(()=>{if(near)setLoaded(previous=>previous.includes(environment)?previous:[...previous,environment])},[near,environment]);
  return <div ref={ref} className="environment-scene" aria-hidden="true">{loaded.map(name=><img key={name} className={name===environment?'visible':''} src={asset(`scene-bg-${name}.jpg`)} alt="" decoding="async"/>)}</div>;
}
function Eyebrow({children}) {return <p className="eyebrow">{children}</p>}
function SectionHead({eyebrow,title,text}) {return <div className="section-head"><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Lightbox({items,index,onClose,onChange}) {
  const ref=useRef(null);
  useEffect(()=>{const overflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current.showModal();return()=>{document.body.style.overflow=overflow}},[]);
  const item=items[index];
  return <dialog ref={ref} className="lightbox" onCancel={e=>{e.preventDefault();onClose()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();onChange((index+1)%items.length)}if(e.key==='ArrowLeft'){e.preventDefault();onChange((index+items.length-1)%items.length)}}} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={item.title}>
    <div className="lightbox-inner"><div className="lightbox-top"><span>{item.title}</span><button className="icon-button" onClick={onClose} autoFocus aria-label="关闭放大画面">×</button></div><img src={asset(item.src)} alt={item.title}/>{items.length>1&&<div className="lightbox-bottom"><button className="button quiet" onClick={()=>onChange((index+items.length-1)%items.length)} aria-label="上一张">←</button><span>{index+1} / {items.length}</span><button className="button quiet" onClick={()=>onChange((index+1)%items.length)} aria-label="下一张">→</button></div>}</div>
  </dialog>
}
function IPhoneFrame({children,className=''}) {return <div className={`iphone-mockup ${className}`}><div className="iphone-screen">{children}</div><img className="iphone-hardware" src={asset('iphone17pro-silver.webp')} alt="" aria-hidden="true" loading="lazy"/></div>}
function PhonePreview({src,title,priority=false,index=0,mode}) {const items=[].concat(src),titles=[].concat(title);return <IPhoneFrame><div className="iphone-original"><ScreenDeck index={items.length>1?index:0} mode={mode}>{items.map((s,i)=><img key={s} className="native-screen" src={asset(s)} alt={titles[i]??titles[0]} loading={priority?'eager':'lazy'} decoding="async"/>)}</ScreenDeck></div></IPhoneFrame>}
function CrayonHeadline() {return <h1 className="crayon-headline"><span className="headline-text">把恢复，练成日常。</span><span className="headline-desktop" aria-hidden="true"><span className="headline-art headline-desktop-first"><img src={asset('hero-title-transparent.png')} alt="" fetchPriority="high"/></span><span className="headline-art headline-desktop-second"><img src={asset('hero-title-transparent.png')} alt=""/></span></span><span className="headline-mobile headline-art" aria-hidden="true"><img src={asset('hero-title-transparent.png')} alt=""/></span></h1>}

export function App() {
  const [screen,setScreen]=useState(0),[feature,setFeature]=useState(0),[tape,setTape]=useState(0),[environment,setEnvironment]=useState('家中'),[box,setBox]=useState(null),[music,setMusic]=useState(false),[menu,setMenu]=useState(false),[playing,setPlaying]=useState(false);
  const video=useRef(null),audio=useRef(null),opener=useRef(null);
  useSmoothScroll();
  const open=(items,index=0)=>{opener.current=document.activeElement;setBox({items,index})};
  const close=()=>{setBox(null);requestAnimationFrame(()=>opener.current?.focus())};
  const lightboxChange=index=>setBox(previous=>({...previous,index}));
  const guides=Array.from({length:6},(_,i)=>({src:`guide_${i+1}.png`,title:`康复指南与文献 ${i+1}`}));
  useEffect(()=>{
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));
    const pause=()=>{if(document.hidden){video.current?.pause();audio.current?.pause()}};document.addEventListener('visibilitychange',pause);
    return()=>{observer.disconnect();document.removeEventListener('visibilitychange',pause)};
  },[]);
  useEffect(()=>{video.current?.pause();setPlaying(false)},[feature]);
  useEffect(()=>{if(!video.current)return;const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)video.current?.pause()},{threshold:.15});observer.observe(video.current);return()=>observer.disconnect()},[feature]);
  const toggleVideo=async()=>{if(!video.current)return;if(video.current.paused){try{await video.current.play()}catch{setPlaying(false)}}else video.current.pause()};
  const toggleMusic=async()=>{if(audio.current.paused){try{await audio.current.play()}catch{setMusic(false)}}else audio.current.pause()};
  const tabKeys=e=>{if(!['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;const tabs=[...e.currentTarget.querySelectorAll('[role=tab]')];const i=tabs.indexOf(e.target);if(i<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(['ArrowRight','ArrowDown'].includes(e.key)?1:tabs.length-1))%tabs.length;tabs[next].click();tabs[next].focus();tabs[next].scrollIntoView({block:'nearest',inline:'nearest'})};
  const f=features[feature];const tapeImages=['iphone-tape.png','iphone-tape-step2.png','iphone-tape-step7.png'];
  return <>
    <a className="skip" href="#main">跳到主要内容</a>
    <nav className="nav"><a className="brand" href="#" aria-label="ReACL 首页"><img src={asset('logo_white.png')} alt="ReACL" width="797" height="279"/></a><button className="mobile-menu button quiet" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="nav-links">{menu?'关闭':'菜单'}</button><div id="nav-links" className={`nav-links ${menu?'open':''}`} onClick={()=>setMenu(false)}><a href="#journey">康复路径</a><a href="#app">App 功能</a><a href="#lab">Pro 实验室</a><a href="#evidence">循证依据</a></div><a className="button quiet nav-cta" href="#get">立即获取 <span aria-hidden="true">↗</span></a></nav>
    <main id="main">
      <header className="hero"><div className="hero-copy"><Eyebrow>REACL · ACL 术后阶段化康复</Eyebrow><CrayonHeadline/><p className="hero-subtitle">科学的阶段化训练，陪你一步步重返运动。</p><div className="actions"><Download/><button className="button quiet" onClick={()=>open([{src:'qrcode_miniprogram.jpg',title:'微信扫码体验 ReACL 小程序'}])}>体验小程序 <span aria-hidden="true">↗</span></button></div></div>
        <HeroStage>
          <img className="hero-art" src={asset('hero-paper-theatre.png')} alt="蜡笔运动员、纸跑道与剪纸动作卡片" fetchPriority="high"/>
          <div className="stage-label"><span>从术后第一步</span><strong>到重返赛场</strong></div>
          <div className="hero-phone"><PhonePreview src="iphone-daily.png" title="ReACL 今日训练 · 原生 App 画面" priority/><span className="paper-label">ReACL · 今日训练</span></div>
        </HeroStage>
        <div className="hero-proof"><div><strong>7 个阶段，循序渐进。</strong><p>明确的进阶目标，让恢复更有方向。</p></div><div><strong>170+ 动作，持续更新。</strong><p>家中或健身房，让训练融入日常。</p></div><div><strong>回到你热爱的运动。</strong><p>认真练好每一步，再出发。</p></div></div></header>
      <section id="journey" className="section journey" data-reveal><SectionHead eyebrow="01 / 一步一步，走得更稳" title={<>7 个阶段。<br/>每一步，都有方向。</>} text="从保护到强化，再到重返运动。根据阶段目标与晋级指标前进，让训练跟上你的恢复。"/><ol className="phase-path" aria-label="七个康复阶段">{phases.map((p,i)=><li key={i}><span className="phase-tab-number">0{i+1}</span><img className="phase-tab-art" src={asset(`acl-phase-icon-${i+1}.png`)} alt="" loading="lazy"/><span className="phase-tab-name">{p[0]}</span></li>)}</ol></section>
      <section id="daily" className="section daily" data-reveal><div className="daily-copy"><Eyebrow>02 / 每天量身定制 · PRO</Eyebrow><h2>按当天状态，<br/>安排今天的训练。</h2><p>结合恢复状态、手术时间、半月板情况与训练反馈，动态调整每日计划。家中或健身房，都能找到合适的训练方式。</p><AnimatedOptions className="segmented" active={environment} role="group" aria-label="训练环境">{['家中','健身房'].map(item=><button key={item} aria-pressed={environment===item} className={environment===item?'active':''} onClick={()=>setEnvironment(item)}>{item}</button>)}</AnimatedOptions><div className="environment-copy" key={environment} aria-live="polite"><strong>{environment==='家中'?'让日常空间，成为训练场。':'在力量训练里，继续进阶。'}</strong><p>{environment==='家中'?'根据可用器材与阶段，安排适合在家完成的动作。':'根据训练环境调整动作安排，逐步建立力量与控制。'}</p></div><a className="text-link" href="#compare">看看 Free 与 Pro 的区别 <span>↗</span></a></div><div className="daily-visual" data-environment={environment==='家中'?'home':'gym'}><EnvironmentScene environment={environment==='家中'?'home':'gym'}/><Parallax range={26} className="parallax-phone"><PhonePreview src="iphone-daily.png" title="今日训练计划"/></Parallax></div></section>
      <section id="app" className="section app-section" data-reveal><SectionHead eyebrow="03 / 装进口袋的个人运动训练" title={<>训练与恢复，<br/>随时可见。</>} text="原生 iPhone 体验，让每日训练和恢复进程随时可见。"/><div className="app-showcase"><AnimatedOptions active={screen} className="app-selector" role="tablist" onKeyDown={tabKeys} aria-label="App 真实画面">{screens.map((item,i)=><button key={item[0]} id={`screen-tab-${i}`} role="tab" tabIndex={screen===i?0:-1} aria-controls="screen-panel" aria-selected={screen===i} className={screen===i?'active':''} onClick={()=>setScreen(i)}><span>0{i+1}</span><div><strong>{item[0]}</strong><p>{item[2]}</p></div><span aria-hidden="true">↗</span></button>)}<Download quiet/></AnimatedOptions><div className="app-phone-frame" id="screen-panel" role="tabpanel" aria-labelledby={`screen-tab-${screen}`}><PhonePreview src={screens.map(item=>item[1])} index={screen} title={screens.map(item=>`ReACL iPhone ${item[0]}`)}/></div></div><div className="app-extras">{[['coach-weekly-summary.png','每周回顾','回看训练数据，理解本周的积累。'],['nutrition-hero-icon.png','每日食谱','每日三餐与加餐，可调整偏好与菜式。'],['acl-phase-icon-7.png','阶段解读','每次晋级，理解接下来的目标。'],['rts-hero-icon.png','重返运动评估','汇总回归前指标，形成评估报告。']].map(([src,title,text])=><article key={title}><img src={asset(src)} alt="" loading="lazy"/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="lab" className="lab-wrap"><div className="section lab" data-reveal><SectionHead eyebrow="04 / iOS APP · PRO" title={<>动作指导，<br/>看清楚再开始。</>} text="动作指导与实验室，让你更具体地理解自己的训练。"/><AnimatedOptions active={feature} className="feature-tabs" role="tablist" onKeyDown={tabKeys} aria-label="Pro 动作指导与实验室">{features.map((item,i)=><button key={item.id} id={`feature-tab-${i}`} role="tab" tabIndex={feature===i?0:-1} aria-selected={feature===i} aria-controls="feature-panel" className={feature===i?'active':''} onClick={()=>setFeature(i)}><img src={asset(item.art)} alt="" loading="lazy"/><strong>{item.title}</strong><span>↗</span></button>)}</AnimatedOptions><div className="feature-panel" role="tabpanel" id="feature-panel" aria-labelledby={`feature-tab-${feature}`}><div className="feature-copy" key={f.id}><span className="mini-label">REACL PRO / 0{feature+1}</span><h3>{f.heading.split('，').map((part,i)=><React.Fragment key={i}>{i>0&&<br/>}{part}{i===0?'，':''}</React.Fragment>)}</h3><p>{f.text}</p><ul>{f.notes.map(n=><li key={n}>{n}</li>)}</ul>{feature===0&&<p className="small-note">实时摄像头计数仅支持 iPhone 的部分动作；iPad 实验室支持导入视频评估。</p>}{feature===1&&<button className="button primary" onClick={toggleVideo} aria-pressed={playing}>{playing?'暂停演示':'播放真实 3D 演示'} <span>{playing?'Ⅱ':'▷'}</span></button>}{feature===2&&<div className="tape-controls"><p className="small-note">查看三个实际步骤画面</p><AnimatedOptions className="segmented" active={tape}>{['完整效果','步骤 2','步骤 7'].map((name,i)=><button key={name} aria-pressed={tape===i} className={tape===i?'active':''} onClick={()=>setTape(i)}>{name}</button>)}</AnimatedOptions></div>}<p className="small-note feature-note">{feature===0?'需 Pro；单腿蹲与 CMJ 分别从阶段 4、6 开放。':feature===1?'需 Pro；部分动作提供 3D 演示。':'需 Pro；膝盖防护贴扎演示适用于所有阶段。'}</p></div><figure className={`feature-media ${feature===0?'assessment':''}`}><DeviceSwap id={feature} className="feature-device">{feature===1?<IPhoneFrame><video ref={video} src={asset('iphone-demo3d-web.mp4')} poster={asset('iphone-demo3d.png')} preload="none" playsInline muted loop controls onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} aria-label="App 原生高脚杯深蹲 3D 演示录屏"/></IPhoneFrame>:<PhonePreview src={feature===2?tapeImages:f.image} index={feature===2?tape:0} mode="fade" title={feature===2?['完整效果','步骤 2','步骤 7'].map(name=>`肌贴${name}`):f.caption}/>}</DeviceSwap><figcaption>{f.caption}</figcaption></figure></div></div></section>
      <section id="evidence" className="section evidence" data-reveal><SectionHead eyebrow="05 / 每一步，皆有据可依" title={<>有温度的训练。<br/>有依据的选择。</>} text="康复动作与晋级标准，参考运动医学文献与指南。把科学的依据，放进每天的训练。"/><div className="guide-shelf">{guides.map((g,i)=><Parallax key={g.src} range={[14,-10,18,-6,12,-14][i]} className="guide-drift"><figure className="guide"><img src={asset(g.src)} alt={g.title} loading="lazy"/><figcaption>0{i+1}</figcaption></figure></Parallax>)}</div></section>
      <section id="compare" className="section pricing" data-reveal><SectionHead eyebrow="06 / 找到适合你的训练方式" title={<>Free 建立基础。<br/>Pro 个性化进阶。</>} text="Free 帮你建立基础。Pro 把计划、训练和反馈，连成更贴近你的每一天。"/><div className="pro-intro"><div className="pro-intro-copy"><span className="mini-label">REACL PRO</span><h3>每天的训练，<br/>更贴近今天的你。</h3><p>结合状态与近期记录调整计划，配合更丰富的动作和指导。</p><a className="button primary" href="#get">查看获取方式 <span aria-hidden="true">↗</span></a></div><div className="pro-highlights"><div><span className="pro-highlight-label">个性化计划</span><strong>每天，<br/>量身调整。</strong><p>结合恢复状态与训练环境安排动作</p></div><div><span className="pro-highlight-label">更丰富的动作库</span><strong><CountUp to={170}/><span className="plus">+</span></strong><p>基础动作与进阶训练，持续更新</p></div><div><span className="pro-highlight-label">动作指导与实验室</span><strong>看清楚，再练好。</strong><p>iPhone 摄像头计数 · 动作评估 · 3D 与肌贴步骤</p></div></div></div><div className="comparison-scroll"><table><thead><tr><th scope="col">功能</th><th scope="col"><span>FREE</span><small>基础康复</small></th><th scope="col" className="pro-column-head"><span>PRO</span><small>个性化进阶 · 训练与反馈连起来</small></th></tr></thead><tbody>{comparison.map(([name,free,pro])=><tr key={name}><th scope="row">{name}</th><td data-plan="FREE">{free}</td><td data-plan="PRO"><div className="pro-value"><span className="pro-check" aria-hidden="true">✓</span><span>{pro}</span></div></td></tr>)}</tbody></table></div><p className="comparison-note">重返运动评估需 Pro 且术后满 9 个月，部分指标需线下测量；摄像头计数仅限 iPhone 的支持动作。</p><div className="shared"><div><strong>基础记录功能，无需升级。</strong><p>角度、腿围、训练打卡与报告存档，Free 与 Pro 均可使用。</p></div><a className="text-link" href="#get">查看获取方式 ↗</a></div></section>
      <section id="get" className="section get" data-reveal><SectionHead eyebrow="从今天，开始积累" title={<>下载 ReACL，<br/>开始今天的训练。</>} text="选择适合你的使用方式。"/><div className="get-grid"><div className="get-app"><img className="get-illustration" src={asset('acl-phase-icon-6.png')} alt="App 蜡笔慢跑插画" loading="lazy"/><h3>iPhone 与 iPad</h3><Download/><p>下载后在 App 内开通 Pro（应用内购买）。</p></div><div className="get-wechat"><h3>微信小程序</h3><div className="qrs">{[['qrcode_miniprogram.jpg','进入小程序体验'],['qrcode_wechat.png','开通 Pro 客服（仅小程序）']].map(([src,title])=><figure key={src}><img src={asset(src)} alt={title} loading="lazy"/><figcaption>{title}</figcaption></figure>)}</div><p>使用微信扫码进入。</p></div></div></section>
    </main>
    <footer className="footer"><div className="footer-top"><a className="brand" href="#" aria-label="回到顶部"><img src={asset('logo_white.png')} alt="ReACL"/></a><p>一步一步，重返你热爱的运动。</p><a href="#privacy" onClick={()=>{document.getElementById('privacy').open=true}}>隐私政策</a></div><details id="privacy" className="privacy"><summary>隐私政策 <span>更新日期：2026 年 6 月 1 日</span></summary><p>ReACL 重视并保护用户隐私。我们仅在提供康复计划、训练记录、AI 个性化建议和购买服务所必需的范围内处理信息。</p><div className="privacy-grid">{[['信息收集','我们可能收集你的账号信息、康复阶段、训练完成情况、主观疲劳反馈、购买状态以及设备运行所需的基础日志信息。'],['使用目的','相关信息用于生成和调整康复训练计划、记录恢复进度、提供 PRO 功能、排查故障并提升产品体验。'],['信息保护','我们会采取合理的安全措施保护你的信息，不会出售用户个人信息，也不会将信息用于与 ReACL 服务无关的用途。'],['第三方服务','如涉及支付、登录、数据存储或统计分析，相关第三方服务仅会在完成对应功能所需范围内处理必要信息。']].map(([t,p])=><div key={t}><h3>{t}</h3><p>{p}</p></div>)}</div><p>如需访问、更正或删除个人信息，或对本政策有疑问，请通过页面中的二维码联系我们。</p></details><div className="footer-bottom"><span>© ReACL</span><button className="music-control" onClick={toggleMusic} aria-pressed={music}>{music?'Ⅱ 暂停音乐':'▷ 播放音乐'}</button></div><audio ref={audio} src={asset('background-music.mp3')} loop preload="none" onPlay={()=>setMusic(true)} onPause={()=>setMusic(false)}/></footer>
    {box&&<Lightbox items={box.items} index={box.index} onChange={lightboxChange} onClose={close}/>}
  </>;
}
